### ISSUE TITLE
changed bar location/size compatibility

### ISSUE THREAD

**Issue by d1no1** [ironmonk88/hotbar-expansion#12]
please add compatibility for UI or otherwise modules that change the macro bar positioning and/or size so the following doesn't come to pass:

![brave_3t7wGg5BaG](https://user-images.githubusercontent.com/88597883/128613935-3db27df1-0584-46bb-9a17-45058b7daf89.png)

TY!

**Comment by ironmonk88** [comment]
Should be fixed with the latest release.
