### ISSUE TITLE
[BUG] New options break the layout

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/hotbar-expansion#13]
Hello,

Thx for merging the PR!
Altough, there are some issue with fewer bars & reverse option activated.

![image](https://user-images.githubusercontent.com/1687854/130372597-629ec9a0-8a6c-4c2f-8211-3e1474534def.png)

1. There is a gap after the macro slot on the right-hand side
2. There is a gap between the main hotbar and the expansion.

Tested with all modules disabled, expect "hotbar-expansion" on 5e 1.4.2 & FVTT 0.8.9

**Comment by ironmonk88** [comment]
What version of Hotbar are you using?  There were 3 in a row due to small issues.

**Comment by ironmonk88** [comment]
The bottom gap should only be active if custom hotbar is active.
The one to the right is only if RPG UI is active.

I'm not able to replicate with the latest version.

**Comment by DarKDinDoN** [comment]
@ironmonk88 I can replicate on a brand-new world with 5e 1.4.2 and FVTT 0.8.9

![image](https://user-images.githubusercontent.com/1687854/130373210-734a9751-ffcf-4791-98ac-eba271c9a4b7.png)

No "custom hotbar", no "RPG UI" installed or active

**Comment by DarKDinDoN** [comment]
@ironmonk88 Was testing in a browser.
Just tested in the electron app, and I have the same behavior in a blank world.

**Comment by ironmonk88** [comment]
Try uninstalling Hotbar Expansion and then re-installing it.

**Comment by DarKDinDoN** [comment]
@ironmonk88 made the test on a linux server and on electron.
Uninstalled and installed again. Still have the issue.

I'm thinking it's not my setup that is not up to date, but rather yours.
Did you try in a blank world with 5e 1.4.2, FVTT 0.8.9 and only this module activated?

**Comment by ironmonk88** [comment]
Yeah.  Completely blank world.  Matched your settings.  Uninstalled the Hotbar Expansion and reinstalled it.
All versions of everything match. 5e 1.4.2, FVTT 0.8.9, with only Hotbar activated.

I'm on a Windows server instead of a Linux but that shouldn't be an issue.

Are you on my Discord Server?
