### ISSUE TITLE
Hotbars warp around when zoomed out using browser's zoom.

### ISSUE THREAD

**Issue by yoshisman8** [ironmonk88/hotbar-expansion#14]
My monitor resolution is just slightly small enough to require me to have foundry at 90% zoom to see things and as of the current version of this module (1.0.11) the hotbars now wrap around when in any zoom other than 100%

![image](https://user-images.githubusercontent.com/4214215/141180452-3d99fe2e-0d7d-44d1-bf21-df0351cabd70.png)

![image](https://user-images.githubusercontent.com/4214215/141180616-ee4146e3-1be0-4e29-b9ce-9ac9f93f6950.png)

**Browser**: Google Chrome

**Screen Resolution**: 1600x900

This wasn't an issue before until this update, please fix this so that the hotbars don't warp around anymore

**Comment by ironmonk88** [comment]
I think this should be fixed in the latest version.
