### ISSUE TITLE
[BUG] Dragging an icon to a hotbar creates two macros

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/hotbar-expansion#15]
Hello,

FVTT 0.8.9
5e 1.5.5
hotbar-expansion 1.0.11

From a character sheet, dragging an icon (like a spell or a weapon) to a hotbar creates the macro twice:
![image](https://user-images.githubusercontent.com/1687854/145679449-856c7c47-3293-414b-bdc5-c7789f4c3ba9.png)

**Comment by DarKDinDoN** [comment]
@ironmonk88 just a few debugs:

removing line https://github.com/ironmonk88/hotbar-expansion/blob/main/hotbar-expansion.js#L85 seems to fix the issue at hand, but remove the drag & drop capability

**Comment by DarKDinDoN** [comment]
@ironmonk88 I think I have the fix.

Changing this line https://github.com/ironmonk88/hotbar-expansion/blob/main/hotbar-expansion.js#L55 with:
`app._dragDrop[0].dropSelector = ".macro";`

Appears that `"#macro-list,.macro-list"` is redundant, creating some listeners twice for the module's hotbar.

**Comment by git-kor-av** [comment]
This issue is still happening, any chance there's a plan to fix this?

@DarKDinDoN - can you confirm that this fixed the issue without any side effects?
