### ISSUE TITLE
Minimal UI friendliness

### ISSUE THREAD

**Issue by saif-ellafi** [ironmonk88/hotbar-expansion#20]
Hey monk!!

Do you need this setting in V9 and moving forward?
![image](https://user-images.githubusercontent.com/27952699/147849038-3ca65daa-4663-4adb-805c-7a1507b1a107.png)

If you manage to remove it or not need it, the module would be much more friendlier with Minimal UI's hotbar positioning. Or if possible, disable it when Minimal UI is enabled to give my side priority :)

Looking forward to combine the two better! For now, with this, I am forced to disable some patches in Minimal UI, disabling some features.

Thanks!

**Comment by ironmonk88** [comment]
Unfortunately I do in v9.
That's one of the things that broke.

That being said... it was a quick patch and I didn't look into it further and if you can find a way around it that works with minimal UI I'd be happy to update it. :-)

**Comment by saif-ellafi** [comment]
Thanks! But is it a positioning matter? because I was wondering if you could only disable the style when Minimal UI is active, as it already takes care of positioning of the Hotbar. To my testing so far, disabling it while Minimal UI is enabled seems perfectly fine.

**Comment by saif-ellafi** [comment]
Ok, worked around this on Minimal UI's side.
