### ISSUE TITLE
V9 Warning Tag

### ISSUE THREAD

**Issue by brunocalado** [ironmonk88/hotbar-expansion#21]
Hi.

Can you remove the v9 warning tag?
![image](https://user-images.githubusercontent.com/4999783/148126349-249218b8-412c-47bd-9e70-47c71869d2b5.png)

replace   "compatibleCoreVersion":"0.9.0", by    "compatibleCoreVersion":"9",

**Comment by ironmonk88** [comment]
Closing the ticket as this should have been fixed awhile ago.
