### ISSUE TITLE
Getting 'cannot read properties of undefined' every time I trigger a macro from the hotbar

### ISSUE THREAD

**Issue by ctbritt** [ironmonk88/hotbar-expansion#23]
Getting this error every time i save a macro that's in the hotbar: 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
[Detected 1 package: monks-hotbar-expansion]
    at DragDrop.bind (foundry.js:44274:31)
    at foundry.js:3333:35
    at Array.forEach (<anonymous>)
    at CustomHotbar._activateCoreListeners (foundry.js:3333:20)
    at Function.renderHotbar (hotbar-expansion.js:85:17)

```
    
Doesn't seem to mess with anything, so non-urgent?

**Comment by ironmonk88** [comment]
I believe this was an issue with Build 249.
Try upgrading to 255 and see if it's still an issue.

**Comment by ironmonk88** [comment]
Never mind... looks like it's a conflict with Custom Hotbar.

**Comment by Ghorin46** [comment]
> Never mind... looks like it's a conflict with Custom Hotbar.

It seems you are right :
- i got the issue even after upgrading to 255
- i got the issue when both Custom Hotbar and Monk's Hotbat Expansion modules are loaded
- I don't have the issue when I remove the Custom Hotbar module

**Comment by ironmonk88** [comment]
The latest version of Hotbar should have fixed this.
