### ISSUE TITLE
Uncaught (in promise) error

### ISSUE THREAD

**Issue by Motara7** [ironmonk88/hotbar-expansion#24]
Foundry Version 9; Build 249
Pathfinder 1 0.80.9
Monk's Hotbar Expansion 1.0.12

I get the following error when I start Foundry:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
[Detected 1 package: monks-hotbar-expansion]
    at DragDrop.bind (foundry.js:44281:31)
    at foundry.js:3333:35
    at Array.forEach (<anonymous>)
    at CustomHotbar._activateCoreListeners (foundry.js:3333:20)
    at Function.renderHotbar (hotbar-expansion.js:85:17)

It doesn't seem to cause any problems with functionality, but I'm trying to clean up errors and was wondering what causes this.

**Comment by Ghorin46** [comment]
This is the same issue than #23.

**Comment by ironmonk88** [comment]
See the other issue for more details.
