### ISSUE TITLE
Reverse Setting needs update to show properly

### ISSUE THREAD

**Issue by MrChessur** [ironmonk88/hotbar-expansion#25]
Basically, When reverse setting is on and I expand the hotbars, they open up non-reversed. If I then press the arrow keys it updates and rearranges them to be reversed. But if I close it and re-open it is returns to normal, non-reversed.

**Comment by jocolamarco** [comment]
+1

Screenshot:
![image](https://user-images.githubusercontent.com/45291719/158071580-309d294e-c992-4002-9050-6644ff7ca2f3.png)

**Comment by Doresain** [comment]
Same issue. Not the end of the world, but would be awesome if this worked.

**Comment by AmazingVanish** [comment]
+1 came here to request exactly this.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
