### ISSUE TITLE
Can't collapse expanded hotbars

### ISSUE THREAD

**Issue by Mr-Monocyte** [ironmonk88/hotbar-expansion#5]
I'm using the most recent 0.7.9 build of Foundry VTT

After activating the module, all 5 hot bars are expanded immediately but clicking on the hot bar number at the bottom doesn't collapse them. The only way I can remove them from view is to collapse the entire hot bar window.

**Comment by ironmonk88** [comment]
Cleaning up tickets.  Closing this ticket because of it's age and we're into v10 now.
