### ISSUE TITLE
Recognize use of Custom Hotbar and render above it

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/hotbar-expansion#8]
Currently Hotbar Expansion renders over the Custom Hotbar. It if can recognize the use of that mod, it could potentially move the drawer to render above it, so Custom Hotbar can still be used.

![image](https://user-images.githubusercontent.com/4083812/127732088-c41aee38-987e-4fe3-8b5c-dc7d42303660.png)

**Comment by ironmonk88** [comment]
Should be corrected in the latest release.
